application: curiosityfeeds
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app

- url: /getfeeds
  script: feeds.getfeeds.app

- url: /images
  script: feeds.imagesfeed.app